#!/usr/bin/env python3
"""
FarmerApp — UI Test Report Generator
=====================================
Reads a Maestro report directory and produces:
  - report.html   : Bootstrap HTML report with screenshots embedded
  - summary.json  : Machine-readable pass/fail counts for CI

Usage: python3 scripts/generate_report.py <report_dir>
"""

import sys
import json
import base64
import xml.etree.ElementTree as ET
from pathlib import Path
from datetime import datetime

# ── HTML Template ─────────────────────────────────────────────────────────────
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>FarmerApp UI Test Report — {timestamp}</title>
  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
    crossorigin="anonymous"
  />
  <style>
    body {{ font-family: 'Segoe UI', sans-serif; background: #f8f9fa; }}
    .stat-card {{ border-radius: 12px; }}
    .screenshot-img {{ border-radius: 8px; border: 1px solid #dee2e6; cursor: zoom-in; }}
    .crash-pre {{ font-size: 0.75rem; max-height: 300px; overflow-y: auto; }}
    .flow-badge {{ font-size: 0.7rem; }}
  </style>
</head>
<body class="p-4">

<div class="d-flex align-items-center mb-3">
  <h1 class="me-3">🌾 FarmerApp UI Test Report</h1>
  <span class="badge bg-secondary fs-6">{timestamp}</span>
</div>

<!-- Summary cards -->
<div class="row g-3 mb-4">
  <div class="col-sm-3">
    <div class="card stat-card text-bg-{overall_class} text-center p-3">
      <div class="display-5 fw-bold">{total}</div>
      <div>Total Tests</div>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="card stat-card text-bg-success text-center p-3">
      <div class="display-5 fw-bold">{passed}</div>
      <div>Passed ✅</div>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="card stat-card text-bg-danger text-center p-3">
      <div class="display-5 fw-bold">{failed}</div>
      <div>Failed ❌</div>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="card stat-card text-bg-warning text-center p-3">
      <div class="display-5 fw-bold">{crashes}</div>
      <div>Crash Lines ⚡</div>
    </div>
  </div>
</div>

<!-- Failures -->
{failures_section}

<!-- Crash logs -->
{crashes_section}

<!-- Screenshots -->
{screenshots_section}

<hr class="mt-5"/>
<p class="text-muted text-center small">
  Generated by FarmerApp Test Suite · {timestamp}
</p>

<script>
  // Click screenshot to open full-size in new tab
  document.querySelectorAll('.screenshot-img').forEach(img => {{
    img.addEventListener('click', () => {{
      const w = window.open();
      w.document.write('<img src="' + img.src + '" style="max-width:100%">');
    }});
  }});
</script>
</body>
</html>"""


def parse_junit(xml_path: Path):
    """Returns (failures list, passed count, total count)."""
    if not xml_path.exists():
        return [], 0, 0

    failures, passed, total = [], 0, 0
    try:
        tree = ET.parse(xml_path)
        for tc in tree.getroot().iter("testcase"):
            total += 1
            f = tc.find("failure") or tc.find("error")
            if f is not None:
                msg = (f.text or f.get("message", "No detail")).strip()
                failures.append({
                    "name": tc.get("name", "unknown"),
                    "flow": tc.get("classname", ""),
                    "time": tc.get("time", "?"),
                    "message": msg[:1200],
                })
            else:
                passed += 1
    except ET.ParseError as e:
        print(f"⚠️  Could not parse {xml_path}: {e}")

    return failures, passed, total


def embed_screenshots(screenshot_dir: Path, max_count: int = 50) -> str:
    if not screenshot_dir.exists():
        return ""

    images = sorted(screenshot_dir.glob("*.png"))[:max_count]
    if not images:
        return ""

    cards = ""
    for img_path in images:
        try:
            b64 = base64.b64encode(img_path.read_bytes()).decode()
            cards += f"""
            <div class="col-6 col-md-3 mb-3">
              <img
                class="screenshot-img img-fluid w-100"
                src="data:image/png;base64,{b64}"
                title="{img_path.stem}"
                alt="{img_path.stem}"
              />
              <div class="text-center text-muted small mt-1">{img_path.stem}</div>
            </div>"""
        except Exception:
            pass

    return f"""
<h3 class="mt-4">📸 Screenshots ({len(images)} captured)</h3>
<div class="row">{cards}</div>"""


def build_failures_section(failures) -> str:
    if not failures:
        return '<div class="alert alert-success">✅ All flows passed!</div>'

    html = f"<h3 class='mt-4 text-danger'>❌ Failed Flows ({len(failures)})</h3>"
    for f in failures:
        html += f"""
<div class="card border-danger mb-3">
  <div class="card-header bg-danger text-white d-flex justify-content-between">
    <strong>{f['flow']} / {f['name']}</strong>
    <span class="flow-badge badge bg-light text-dark">{f['time']}s</span>
  </div>
  <div class="card-body">
    <pre class="crash-pre mb-0">{f['message']}</pre>
  </div>
</div>"""
    return html


def build_crashes_section(crash_path: Path) -> str:
    if not crash_path.exists():
        return ""

    lines = [l for l in crash_path.read_text(errors="replace").splitlines() if l.strip()]
    if not lines:
        return ""

    content = "\n".join(lines[:200])
    return f"""
<h3 class="mt-4 text-warning">⚡ Crash / ANR Log Lines ({len(lines)} total)</h3>
<pre class="bg-dark text-warning p-3 rounded crash-pre">{content}</pre>"""


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate_report.py <report_dir>")
        sys.exit(1)

    report_dir = Path(sys.argv[1])
    if not report_dir.exists():
        print(f"❌ Report directory not found: {report_dir}")
        sys.exit(1)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Parse results
    failures, passed, total = parse_junit(report_dir / "results.xml")
    failed = len(failures)
    crash_count = 0
    crash_path = report_dir / "crashes.txt"
    if crash_path.exists():
        crash_count = len([l for l in crash_path.read_text().splitlines() if l.strip()])

    # Build HTML
    html = HTML_TEMPLATE.format(
        timestamp=timestamp,
        total=total,
        passed=passed,
        failed=failed,
        crashes=crash_count,
        overall_class="success" if failed == 0 and crash_count == 0 else "danger",
        failures_section=build_failures_section(failures),
        crashes_section=build_crashes_section(crash_path),
        screenshots_section=embed_screenshots(report_dir / "screenshots"),
    )

    # Write outputs
    (report_dir / "report.html").write_text(html, encoding="utf-8")

    summary = {
        "timestamp": timestamp,
        "total": total,
        "passed": passed,
        "failed": failed,
        "crashes": crash_count,
        "result": "PASS" if failed == 0 else "FAIL",
    }
    (report_dir / "summary.json").write_text(json.dumps(summary, indent=2))

    # Console output
    icon = "✅" if failed == 0 else "❌"
    print(f"\n{icon} {summary['result']}")
    print(f"  Total  : {total}")
    print(f"  Passed : {passed}")
    print(f"  Failed : {failed}")
    print(f"  Crashes: {crash_count}")
    print(f"\n  Report : {report_dir}/report.html")
    print(f"  Summary: {report_dir}/summary.json\n")

    sys.exit(0 if failed == 0 else 1)


if __name__ == "__main__":
    main()
